<?php

namespace Basefony\PageBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Search in pages
     *
     * @param $keyword
     * @return array
     */
    public function getTotalCount($keyword)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p.id')
            ->where('p.title LIKE :title')
            ->orWhere('p.content LIKE :content')
            ->setParameter('title',"%$keyword%")
            ->setParameter('content',"%$keyword%")
            ->getQuery()
            ->execute();

        return $query;
    }

    /**
     * Search in pages
     *
     * @param $keyword
     * @return array
     */
    public function searchResultArr($keyword, $pageNumber, $perPage, $sortField = 'id', $ascDesc='ASC')
    {
        return $this->createQueryBuilder('p')
            ->select('p.id, p.title, p.slug')
            ->where('p.title LIKE :title')
            ->orWhere('p.content LIKE :content')
            ->setParameter('title',"%$keyword%")
            ->setParameter('content',"%$keyword%")
            ->orderBy('p.' . $sortField, $ascDesc)
            ->setFirstResult(($pageNumber - 1) * $perPage)
            ->setMaxResults($perPage)
            ->getQuery()
            ->execute();
    }

    /**
     * Find users for page number
     *
     * @param $pageNumber
     * @param $perPage
     * @return mixed
     */
    public function findPage($pageNumber, $perPage, $sortField = 'id', $ascDesc='ASC')
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.' . $sortField, $ascDesc)
            ->setMaxResults($perPage)
            ->setFirstResult(($pageNumber - 1) * $perPage)
            ->getQuery()
            ->execute();
    }
}
